---
collections:
  
  # Community.vmware collection is required for vCenter
  - name: community.vmware
  # Community.windows collection is required to create a DNS record - Also install ansible.windows collection 
  - name: community.windows
  # Microsoft AD collection is required to add a computer to a Microsoft Active Directory domain.
  - name: microsoft.ad
